### ISSUE TITLE
`pip install localnote`出错

### ISSUE THREAD

**Issue by smilingpoplar** [littlecodersh/LocalNote#3]
Collecting localnote
  Downloading LocalNote-1.0.9.zip
Collecting requests (from localnote)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 85kB/s
Collecting markdown (from localnote)
  Downloading Markdown-2.6.6.zip (412kB)
    100% |████████████████████████████████| 419kB 123kB/s
Collecting evernote (from localnote)
  Downloading evernote-1.25.1.tar.gz (140kB)
    100% |████████████████████████████████| 143kB 111kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-0uqg4f1g/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-0uqg4f1g/evernote/

**Comment by littlecodersh** [comment]
@smilingpoplar 感谢你的报错！
就日志来看是官方evernote包出现了问题，是否方便提供你的Python版本和系统版本？

**Comment by smilingpoplar** [comment]
@littlecodersh 哦，是我的pip指向了pip3，改用pip2就可以安装了

**Comment by littlecodersh** [comment]
好的，由于官方evernote包不支持py3，该软件目前只能使用py2的版本。
之后该软件将会随官方evernote包升级到py3。

**Comment by lovese** [comment]
请问升级到py3了吗？
